[package]
name = "netherfire"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
env_logger = "0.9.0"
thiserror = "1.0.31"

async-trait = "0.1.53"
futures = "0.3.21"
itertools = "0.10.3"

once_cell = "1.12.0"

serde_json = "1.0.81"
toml = "0.5.9"

directories = "4.0.1"

furse = "1.2.3"
ferinth = "2.2.2"

zip = "0.6.2"

reflink = "0.1.3"
walkdir = "2.3.2"

hex = "0.4.3"
digest = "0.10.3"

# Insecure AF, but it's what CurseForge supports... :|
sha1 = "0.10.1"
md-5 = "0.10.1"

[dependencies.clap]
version = "3.1.18"
features = ["derive"]

[dependencies.reqwest]
version = "0.11.10"
features = ["stream"]

[dependencies.serde]
version = "1.0.137"
features = ["derive"]

[dependencies.tokio]
version = "1.18.2"
features = ["rt-multi-thread", "macros", "sync", "fs", "io-std", "io-util"]

[dependencies.tokio-util]
version = "0.7.2"
features = ["compat"]
